// RootLayout.js
import { AuthProvider } from "./Providers";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <AuthProvider>
          <main className="flex-grow">{children}</main> {/* ให้ main ใช้พื้นที่ที่เหลือ */}
          <footer className="bg-[#457373] p-5 text-white text-center">
            <p>Covid-19 data in the US</p> {/* Footer ของคุณ */}
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}

